global.jQuery = require('jquery');
global.$ = require('jquery');
global._ = require('lodash');
global.moment = require('moment');
global.SockJS = require('sockjs-client');

require('stompjs');
require('fullcalendar');
require('./node_modules/fullcalendar/dist/gcal');
require('./node_modules/fullcalendar/dist/locale-all');
require('json3');
require('messageformat');
require('bootstrap-sass');
require('jquery-ui');

require('angular');
require('angular-cookies');
require('angular-sanitize');
require('./node_modules/angular-i18n/fi');
require('angular-file-upload');
require('angular-local-storage');
require('angular-resource');
require('angular-translate');
require('angular-translate-interpolation-messageformat');
require('angular-translate-loader-partial');
require('angular-translate-storage-cookie');
require('angular-ui-bootstrap');
require('angular-ui-calendar');
require('angular-loading-bar');
require('@uirouter/angularjs');
require('./node_modules/@uirouter/angularjs/release/stateEvents');
require('angular-ui-sortable');
require('angular-moment');
require('restangular');
require('angulartics');
require('angulartics-google-analytics');
